# Generated by Django 4.2 on 2023-11-22 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes', '0002_rename_user_client'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='User',
        ),
    ]
