# Generated by Django 4.2 on 2023-11-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes', '0003_rename_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=32),
        ),
    ]
